In [1]:
import numpy as np
import calibration

In [3]:
import os

In [2]:
raw_data = np.random.random((100,4))

In [4]:
calib_folder = r'C:\Users\dyeagly\Documents\hall_probe\hall_probe\Hall probe 443-20'

In [11]:
calib_array = calibration.get_xyz_calib_values(calib_folder)
print(calib_array.shape)
for axis in calib_array:
    print(axis)
    print('\n')

(3, 3, 7)
[[2.1600e-01 2.7700e-05 4.7000e-03 3.6900e-03 6.7500e-01 3.4000e-01
  5.7000e+01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00
  1.0000e+00]
 [5.1000e-02 2.1750e-04 3.9586e-03 0.0000e+00 9.4300e-01 3.4000e-01
  5.7000e+01]]


[[6.5000e-02 3.1800e-05 2.1950e-03 4.7000e-04 6.5400e-01 3.4000e-01
  5.7000e+01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00
  1.0000e+00]
 [8.3000e-02 1.8150e-04 1.3675e-03 0.0000e+00 9.1700e-01 3.4000e-01
  5.7000e+01]]


[[3.000e-02 2.770e-05 4.600e-03 1.230e-03 6.760e-01 3.400e-01 5.700e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 1.000e+00]
 [9.200e-02 2.203e-04 3.800e-03 0.000e+00 9.430e-01 3.400e-01 5.700e+01]]




In [23]:
# raw_cleaned = calibration.clean_raw_data(raw_data)
raw_cleaned = np.array([0.050172634, 0.083926075, 0.09408699, -0.002175129])
print(raw_cleaned.shape)
print(raw_cleaned)

(4,)
[ 0.05017263  0.08392608  0.09408699 -0.00217513]


In [24]:
calib_sample = calibration.calib_data(calib_array, raw_cleaned)

In [25]:
calib_sample

array([38.19503622, 61.2468812 , 70.25016685])

In [26]:
np.linalg.norm(calib_sample)

100.7230221521557

In [33]:
a = np.array([[1,2,3], [7,1,4], [2,5,9], [3,3,3]])
print(a, a.shape)

[[1 2 3]
 [7 1 4]
 [2 5 9]
 [3 3 3]] (4, 3)


In [34]:
print(np.linalg.norm(a, axis=1))

[ 3.74165739  8.1240384  10.48808848  5.19615242]
