In [178]:
import numpy as np

In [179]:
start_point = np.array([-50, -50, 0]).astype('float')
print(start_point)

[-50. -50.   0.]


In [180]:
x_length = 200
y_length = 100
z_length = 50
interval = 0.5

In [191]:
end_point_wp = start_point + np.array([x_length, y_length, start_point[2]])
end_point_volume = start_point + np.array([x_length, y_length, z_length])
print(end_point_wp, end_point_volume)

[150.  50.   0.] [150.  50.  50.]


In [182]:
num_waypoints = 4*y_length + 2
print(num_waypoints)
num_y_patterns = int((num_waypoints-2)/4)
print(num_y_patterns)

402
100


In [189]:
x_pattern = np.tile(np.array([end_point_wp[0], end_point_wp[0], start_point[0], start_point[0]]), num_y_patterns)
print(x_pattern, x_pattern.shape)

[150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150.
 -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50.
 150. 

In [184]:
x = x_pattern.copy()
x = np.insert(x, 0, start_point[0])
x = np.append(x, end_point_wp[0])
print(x, x.shape)

[-50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150.
 150. -50. -50. 150. 150. -50. -50. 150. 150. -50. -50. 150. 150. -50.
 -50. 

In [185]:
y = np.array([[i, i] for i in np.arange(start_point[1], end_point_wp[1]+interval, interval)]).flatten()
print(y, y.shape)

[-50.  -50.  -49.5 -49.5 -49.  -49.  -48.5 -48.5 -48.  -48.  -47.5 -47.5
 -47.  -47.  -46.5 -46.5 -46.  -46.  -45.5 -45.5 -45.  -45.  -44.5 -44.5
 -44.  -44.  -43.5 -43.5 -43.  -43.  -42.5 -42.5 -42.  -42.  -41.5 -41.5
 -41.  -41.  -40.5 -40.5 -40.  -40.  -39.5 -39.5 -39.  -39.  -38.5 -38.5
 -38.  -38.  -37.5 -37.5 -37.  -37.  -36.5 -36.5 -36.  -36.  -35.5 -35.5
 -35.  -35.  -34.5 -34.5 -34.  -34.  -33.5 -33.5 -33.  -33.  -32.5 -32.5
 -32.  -32.  -31.5 -31.5 -31.  -31.  -30.5 -30.5 -30.  -30.  -29.5 -29.5
 -29.  -29.  -28.5 -28.5 -28.  -28.  -27.5 -27.5 -27.  -27.  -26.5 -26.5
 -26.  -26.  -25.5 -25.5 -25.  -25.  -24.5 -24.5 -24.  -24.  -23.5 -23.5
 -23.  -23.  -22.5 -22.5 -22.  -22.  -21.5 -21.5 -21.  -21.  -20.5 -20.5
 -20.  -20.  -19.5 -19.5 -19.  -19.  -18.5 -18.5 -18.  -18.  -17.5 -17.5
 -17.  -17.  -16.5 -16.5 -16.  -16.  -15.5 -15.5 -15.  -15.  -14.5 -14.5
 -14.  -14.  -13.5 -13.5 -13.  -13.  -12.5 -12.5 -12.  -12.  -11.5 -11.5
 -11.  -11.  -10.5 -10.5 -10.  -10.   -9.5  -9.5  -

In [187]:
z = np.array([start_point[2]]*num_waypoints)
print(z, z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [188]:
xyz_wp = np.array([x, y, z]).T
print(xyz_wp, xyz_wp.shape)

[[-50.  -50.    0. ]
 [150.  -50.    0. ]
 [150.  -49.5   0. ]
 ...
 [-50.   49.5   0. ]
 [-50.   50.    0. ]
 [150.   50.    0. ]] (402, 3)


In [194]:
z = np.arange(start_point[2], end_point_volume[2]+interval, interval)
print(z, z.shape)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ] (101,)


In [195]:
volume = np.zeros((z.shape[0], x.shape[0], 3))
print(volume.shape)

(101, 402, 3)


In [196]:
for h in range(volume.shape[0]):
    new_z = xyz_wp.copy()
    new_z[:, 2] = z[h]
    volume[h] = new_z
print(volume.shape)

(101, 402, 3)


In [200]:
print(volume[0:5, :10, :])

[[[-50.  -50.    0. ]
  [150.  -50.    0. ]
  [150.  -49.5   0. ]
  [-50.  -49.5   0. ]
  [-50.  -49.    0. ]
  [150.  -49.    0. ]
  [150.  -48.5   0. ]
  [-50.  -48.5   0. ]
  [-50.  -48.    0. ]
  [150.  -48.    0. ]]

 [[-50.  -50.    0.5]
  [150.  -50.    0.5]
  [150.  -49.5   0.5]
  [-50.  -49.5   0.5]
  [-50.  -49.    0.5]
  [150.  -49.    0.5]
  [150.  -48.5   0.5]
  [-50.  -48.5   0.5]
  [-50.  -48.    0.5]
  [150.  -48.    0.5]]

 [[-50.  -50.    1. ]
  [150.  -50.    1. ]
  [150.  -49.5   1. ]
  [-50.  -49.5   1. ]
  [-50.  -49.    1. ]
  [150.  -49.    1. ]
  [150.  -48.5   1. ]
  [-50.  -48.5   1. ]
  [-50.  -48.    1. ]
  [150.  -48.    1. ]]

 [[-50.  -50.    1.5]
  [150.  -50.    1.5]
  [150.  -49.5   1.5]
  [-50.  -49.5   1.5]
  [-50.  -49.    1.5]
  [150.  -49.    1.5]
  [150.  -48.5   1.5]
  [-50.  -48.5   1.5]
  [-50.  -48.    1.5]
  [150.  -48.    1.5]]

 [[-50.  -50.    2. ]
  [150.  -50.    2. ]
  [150.  -49.5   2. ]
  [-50.  -49.5   2. ]
  [-50.  -49.    2. ]
  