In [17]:
import numpy as np

In [18]:
pcs = np.array([[1,0,0],
                [0,1,0],
                [0,0,1]])
hall = np.array([-0.075, 0.233, 0.045])

In [19]:
hall_unit = hall/np.linalg.norm(hall)
print(hall_unit)

[-0.30135553  0.93621119  0.18081332]


In [21]:
h = np.array([-0.045, 0.233])
print(h/np.linalg.norm(h))

[-0.18962881  0.98185585]


In [28]:
hs_theta = np.dot(hall_unit, pcs)/(np.linalg.norm(hall_unit)*np.linalg.norm(pcs))
print(hs_theta)

[-0.1739877   0.54052178  0.10439262]


In [30]:
def rotate(theta_array, vector):
    Rx = np.array([[1, 0, 0],
                   [0, np.cos(theta_array[0]), -np.sin(theta_array[0])],
                   [0, np.sin(theta_array[0]), np.cos(theta_array[0])]])
    Ry = np.array([[np.cos(theta_array[1]), 0, np.sin(theta_array[1])],
                   [0, 1, 0],
                   [-np.sin(theta_array[1]), 0, np.cos(theta_array[1])]])
    Rz = np.array([[np.cos(theta_array[2]), -np.sin(theta_array[2]), 0],
                   [np.sin(theta_array[2]), np.cos(theta_array[2]), 0],
                   [0, 0, 1]])
    R = Rx@Ry@Rz
    return R@vector

In [31]:
rotate(hs_theta, hall)

array([-0.06161975,  0.23602261,  0.04934911])