In [96]:
import numpy as np

In [97]:
sp1_mcs = np.genfromtxt('sp1_mcs.txt', delimiter=' ')
sp1_pcs = np.genfromtxt('sp1_pcs.txt', delimiter=' ')
print(sp1_mcs.round(4))
print(sp1_pcs.round(4))

[[  420.7174 -2442.4588 -1210.9075]
 [  421.5818 -2442.4527 -1210.9061]
 [  421.6157 -2442.4553 -1210.0495]
 [  420.7537 -2442.459  -1210.0755]
 [  421.1445 -2442.4561 -1210.5435]]
[[20.3985  0.4413  8.11  ]
 [21.2629  0.4427  8.1115]
 [21.2967  0.441   8.9681]
 [20.4348  0.4419  8.9421]
 [20.8256  0.4421  8.4741]]


In [98]:
diff = np.genfromtxt('picker_x_mcs.txt', delimiter=' ')
print(diff, diff.shape)

[ 9.99985244e-01 -5.43190543e-03  7.81016932e-05  5.43199877e-03
  9.99984466e-01 -1.24921630e-03 -7.13148552e-05  1.24962212e-03
  9.99999217e-01  4.00320965e+02 -2.44300072e+03 -1.21901665e+03] (12,)


In [99]:
R = diff[:9].reshape((3,3))
Txyz = diff[9:]
print(R, R.shape)
print(Txyz, Txyz.shape)

[[ 9.99985244e-01 -5.43190543e-03  7.81016932e-05]
 [ 5.43199877e-03  9.99984466e-01 -1.24921630e-03]
 [-7.13148552e-05  1.24962212e-03  9.99999217e-01]] (3, 3)
[  400.32096486 -2443.00071753 -1219.01665161] (3,)


In [142]:
asdf = sp1_pcs.copy()
for i in range(sp1_pcs.shape[0]):
    # print(np.round(R@i + Txyz, 4))
    asdf[i] = R@asdf[i] + Txyz
print(asdf.round(4))

[[  420.7174 -2442.4588 -1210.9075]
 [  421.5818 -2442.4527 -1210.9061]
 [  421.6157 -2442.4553 -1210.0496]
 [  420.7537 -2442.459  -1210.0755]
 [  421.1446 -2442.4561 -1210.5435]]


In [101]:
for j in sp1_mcs:
    print(np.round(np.linalg.inv(R)@(j - Txyz), 4))

[20.3985  0.4413  8.11  ]
[21.2629  0.4427  8.1115]
[21.2967  0.441   8.9681]
[20.4348  0.4419  8.9421]
[20.8256  0.4421  8.4741]


In [102]:
mcs_export = np.genfromtxt('mcs_export.txt', delimiter=' ')
mcs_export_T = -mcs_export[:3]
mcs_export_e = mcs_export[3:]
e1, e2, e4 = [np.deg2rad(i) for i in mcs_export_e]
print(mcs_export_T)
print(e1, e2, e4)

[  400.32096486 -2443.00071753 -1219.01665161]
3.198438726506147 0.001251644198044737 3.0793145997728404


In [103]:
Rz1 = np.array([[np.cos(e1), -np.sin(e1), 0],
               [np.sin(e1), np.cos(e1), 0],
               [0, 0, 1]])
Rx = np.array([[1, 0, 0],
               [0, np.cos(e2), -np.sin(e2)],
               [0, np.sin(e2), np.cos(e2)]])
Rz2 = np.array([[np.cos(e4), -np.sin(e4), 0],
                [np.sin(e4), np.cos(e4), 0],
                [0, 0, 1]])
R_mcs_export = np.linalg.inv(Rz1@Rx@Rz2)

In [104]:
R_mcs_export

array([[ 9.99985244e-01, -5.43190552e-03,  7.78995653e-05],
       [ 5.43199861e-03,  9.99984466e-01, -1.24921737e-03],
       [-7.11127245e-05,  1.24962209e-03,  9.99999217e-01]])

In [105]:
for i in sp1_pcs:
    print(np.round(R_mcs_export@i + mcs_export_T, 4))

[  420.7174 -2442.4588 -1210.9075]
[  421.5818 -2442.4527 -1210.9061]
[  421.6157 -2442.4553 -1210.0496]
[  420.7537 -2442.459  -1210.0755]
[  421.1446 -2442.4561 -1210.5435]


In [106]:
sp1_mcs.round(4)

array([[  420.7174, -2442.4588, -1210.9075],
       [  421.5818, -2442.4527, -1210.9061],
       [  421.6157, -2442.4553, -1210.0495],
       [  420.7537, -2442.459 , -1210.0755],
       [  421.1445, -2442.4561, -1210.5435]])

In [108]:
for j in sp1_mcs:
    print(np.round(np.linalg.inv(R_mcs_export)@(j - mcs_export_T), 4))

[20.3985  0.4413  8.11  ]
[21.2629  0.4427  8.1115]
[21.2967  0.441   8.9681]
[20.4348  0.4419  8.9421]
[20.8256  0.4421  8.4741]


In [111]:
print(sp1_pcs.round(4))

[[20.3985  0.4413  8.11  ]
 [21.2629  0.4427  8.1115]
 [21.2967  0.441   8.9681]
 [20.4348  0.4419  8.9421]
 [20.8256  0.4421  8.4741]]
